version: "3.8"

services:
  discovery:
    image: ${DOCKERHUB_REPO}/geoserver-cloud-discovery:${TAG}
    build:
      no_cache: true
      context: ../src/apps/infrastructure/discovery/
      args:
        TAG: ${TAG}

  config:
    image: ${DOCKERHUB_REPO}/geoserver-cloud-config:${TAG}
    build:
      no_cache: true
      context: ../src/apps/infrastructure/config/
      args:
        TAG: ${TAG}

  admin:
    image: ${DOCKERHUB_REPO}/geoserver-cloud-admin-server:${TAG}
    build:
      no_cache: true
      context: ../src/apps/infrastructure/admin/
      args:
        TAG: ${TAG}
    
  gateway:
    image: ${DOCKERHUB_REPO}/geoserver-cloud-gateway:${TAG}
    build:
      no_cache: true
      context: ../src/apps/infrastructure/gateway/
      args:
        TAG: ${TAG}
