# Builds and pushes docker images on main and tags

name: Build and Push Docker images
on:
  push:
    branches:
      - main
      - signed-images
      - "release/**"
    paths:
      - "Makefile"
      - "pom.xml"
      - ".github/workflows/build-and-push.yaml"
      - "config"
      - "src/**"
    tags:
      - '*'

jobs:
  build:
    if: github.repository == 'jemacchi/geoserver-cloud'
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Validate source code formatting
      run: make lint

    - name: Build without tests
      run: |
        make install

    - name: Build images
      run: |
        make build-image

    #- name: Set up private key
    #  run: |
    #    mkdir -p ~/.docker/trust/private/
    #    echo "${{ secrets.SIGN_PRIVATE_KEY }}" > ~/.docker/trust/private/sign.key
    #    chmod 600 ~/.docker/trust/private/sign.key

    #- name: Sign Docker image
    #  run: |
    #    echo $DOCKER_HUB_USERNAME
    #    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="${{ secrets.REPOSITORY_PASSPHRASE }}" docker trust sign ${{ secrets.DOCKER_HUB_USERNAME }}/geoserver-cloud-webui:1.8.3

    - name: Sign and push docker WMS image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: "docker.io/jemacchi/geoserver-cloud-wms:1.9-SNAPSHOT"
        # Example: a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        # The contents from: ~/.docker/trust/private/a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a.key)
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        # Example: myPassw0rdChangeMeReplaceMe
        private-key-passphrase: ${{ secrets.REPOSITORY_PASSPHRASE }}

    - name: Sign and push docker WEBUI image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: "docker.io/jemacchi/geoserver-cloud-webui:1.9-SNAPSHOT"
        # Example: a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        # The contents from: ~/.docker/trust/private/a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a.key)
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        # Example: myPassw0rdChangeMeReplaceMe
        private-key-passphrase: ${{ secrets.REPOSITORY_PASSPHRASE }}

    - name: Sign and push docker WFS image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: "docker.io/jemacchi/geoserver-cloud-wfs:1.9-SNAPSHOT"
        # Example: a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        # The contents from: ~/.docker/trust/private/a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a.key)
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        # Example: myPassw0rdChangeMeReplaceMe
        private-key-passphrase: ${{ secrets.REPOSITORY_PASSPHRASE }}



    #- name: Push images
    #  run: |
    #    make push-image

    - name: Remove project jars from cached repository
      run: |
        rm -rf ~/.m2/repository/org/geoserver
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
