# Builds and pushes docker images on main and tags

name: Build and Push Docker images
on:
  push:
    branches:
      - main
      - signed-images
      - "release/**"
    paths:
      - "Makefile"
      - "pom.xml"
      - ".github/workflows/build-and-push.yaml"
      - "config"
      - "src/**"
    tags:
      - '*'

jobs:
  build:
    if: github.repository == 'jemacchi/geoserver-cloud'
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Validate source code formatting
      run: make lint

    - name: Build without tests
      run: |
        make install

    - name: Build images
      run: |
        make build-image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

    # It's not possible to sign and push images using this bot for multiple repositories (alternative, not to use the bot and do it manually, creating some script to do it)
    - name: Sign and push docker WMS image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: "docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/geoserver-cloud-wms:${{ secrets.RELEASE_TAG }}"
        # Example: a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        # The contents from: ~/.docker/trust/private/a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a.key)
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        # Example: myPassw0rdChangeMeReplaceMe
        private-key-passphrase: ${{ secrets.REPOSITORY_PASSPHRASE }}

    - name: Sign and push docker WFS image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: "docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/geoserver-cloud-wfs:${{ secrets.RELEASE_TAG }}"
        # Example: a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        # The contents from: ~/.docker/trust/private/a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a.key)
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        # Example: myPassw0rdChangeMeReplaceMe
        private-key-passphrase: ${{ secrets.REPOSITORY_PASSPHRASE }}

    - name: Sign and push docker WPS image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: "docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/geoserver-cloud-wps:${{ secrets.RELEASE_TAG }}"
        # Example: a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        # The contents from: ~/.docker/trust/private/a5859a33123cedec334e70ec7709ba8a185a65f485b10c485ce9a84fc917720a.key)
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        # Example: myPassw0rdChangeMeReplaceMe
        private-key-passphrase: ${{ secrets.REPOSITORY_PASSPHRASE }}

    - name: Remove project jars from cached repository
      run: |
        rm -rf ~/.m2/repository/org/geoserver
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
